### ISSUE TITLE
Help running 

### ISSUE THREAD

**Issue by Phe0** [matthias-k/pysaliency#13]
Sorry for the inconvenience, but I'm having trouble running the code provided in the getting started section with octave.

I've installed it using ```pip3 install git+https://github.com/matthias-k/pysaliency.git```
and ran it with python3.

But I'm having the error bellow:

```
Loading DATA/ems i103385030.jpeg
  scalar structure containing the fields:

    message = 'nanmedian' undefined near line 313 column 28
    identifier = Octave:undefined-function
    stack =

      3x1 struct array containing the fields:

        file =
        {
          [1,1] = /tmp/tmpd_xkgbr1/DatabaseCode/checkFixations.m
          [2,1] = /tmp/tmpd_xkgbr1/extract_fixations.m
          [3,1] = /tmp/tmpd_xkgbr1/extract_all_fixations.m
        }


        name =
        {
          [1,1] = checkFixations
          [2,1] = extract_fixations
          [3,1] = extract_all_fixations
        }


        line =
        {
          [1,1] =  313
          [2,1] =  11
          [3,1] =  1118
        }


        column =
        {
          [1,1] =  26
          [2,1] =  19
          [3,1] =  1
        }


        scope =
        {
          [1,1] = []
          [2,1] = []
          [3,1] = []
        }


        context =
        {
          [1,1] = 0
          [2,1] = 0
          [3,1] = 0
        }


  scalar structure containing the fields:

    file = /tmp/tmpd_xkgbr1/DatabaseCode/checkFixations.m
    name = checkFixations
    line =  313
    column =  26
    scope = []
    context = 0
  scalar structure containing the fields:

    file = /tmp/tmpd_xkgbr1/extract_fixations.m
    name = extract_fixations
    line =  11
    column =  19
    scope = []
    context = 0
  scalar structure containing the fields:

    file = /tmp/tmpd_xkgbr1/extract_all_fixations.m
    name = extract_all_fixations
    line =  1118
    column =  1
    scope = []
    context = 0
__ERROR__
Traceback (most recent call last):
  File "aim.py", line 6, in <module>
    mit_stimuli, mit_fixations = pysaliency.external_datasets.get_mit1003(location=dataset_location)
  File "/home/pedrofeo/.local/lib/python3.7/site-packages/pysaliency/external_datasets.py", line 450, in get_mit1003
    return _get_mit1003('MIT1003', location=location, include_initial_fixation=False)
  File "/home/pedrofeo/.local/lib/python3.7/site-packages/pysaliency/external_datasets.py", line 362, in _get_mit1003
    run_matlab_cmd('extract_all_fixations;', cwd=temp_dir)
  File "/home/pedrofeo/.local/lib/python3.7/site-packages/pysaliency/utils.py", line 309, in run_matlab_cmd
    sp.check_call([matlab] + args, cwd=cwd)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/octave', '--traditional', '--eval', "try;extract_all_fixations;;catch exc;struct_levels_to_print(10);print_struct_array_contents(true);disp(lasterror);for i=1:size(lasterror.stack);disp(lasterror.stack(i));end;disp('__ERROR__');exit(1);end;quit"]' returned non-zero exit status 1.
```

**Comment by matthias-k** [comment]
Hi @Phe0 ,

unfortunately octave is not really compatible with Matlab and in my experience gets even less compatible over time. I remember that the code for loading the MIT1003 dataset used to run with octave, but apparently this is not the case anymore. Maybe you need to install some additional packages to make the function `nanmedian` available, but changes are that you need Matlab. I will talk to the owners of the MIT1003 dataset and ask them whether they allow me to put a pysaliency-version of the dataset online.

Best,
  Matthias
